datadog_api_key: "{{ vault_datadog_api_key }}"
datadog_site: "datadoghq.com"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: webapp
        url: "https://{{ app_domain | default('localhost') }}"
        timeout: 5
        method: GET

